wandb_version: 1

DFA:
  desc: null
  value: ParityDFA
num_epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.2
seq_len:
  desc: null
  value: 10
l1_penalty:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721314277
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 3
      - 16
      - 23
      4: 3.10.12
      5: 0.17.4
      8:
      - 5
      13: darwin-x86_64
