wandb_version: 1

name:
  desc: null
  value: trigram
DFA:
  desc: null
  value: ParityDFA
num_epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
max_seq_len:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 10
num_batches:
  desc: null
  value: 100
block_size:
  desc: null
  value: 100
n_layer:
  desc: null
  value: 2
n_head:
  desc: null
  value: 2
n_embd:
  desc: null
  value: 40
MLP_width:
  desc: null
  value: null
trigram:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721735168
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 3
      - 16
      - 23
      4: 3.10.12
      5: 0.17.4
      8:
      - 5
      13: darwin-x86_64
